version: "3.3"

services:
    app:
        build: .
        ports:
            - "8000:8000"
        environment:
            - DEBIAN_FRONTEND=noninteractive
        volumes:
            - ./src:/app

volumes:
    myapp:
